#!/usr/bin/env ruby

env = lambda do
        return ENV['AWS_ENV'] if ENV['AWS_ENV']
        [File.expand_path('~/'), "/etc"].each do |pre|
          %w(production uat developemnt).each {|e| return e if File.exists?("#{pre}/#{e}") }
        end 
        return 'development'
      end.call

config = YAML.load_file("_config/site.yml")
config.merge!(config.fetch("profiles", {}).fetch(env, {}))
port = config[:port] || config['port'] || 4242
bind = config[:bind] || config['bind'] || '127.0.0.1'

fork { exec(%Q{bundle exec thin -R config.ru -p #{port} -a #{bind} -l sinatra/log/thin.log -d start }) }
