title: Simulacre.org
subtitle: Javascript, Ruby and Japan
encoding: UTF-8
disqus: simulacre
google_analytics: 
profiles:
  development:
    base_url: http://localhost/
    disqus_developer: true
  production:
    base_url: http://www.simulacre.org/
    google_analytics: UA-1727701-12
